### ISSUE TITLE
bolo 404 ... 

### ISSUE THREAD

**Issue by necrose99** [D3fy/defiance-overlay#1]
https://github.com/bolo/bolo
https://github.com/bolo/bolo-collectors

https://github.com/filefrog  **404**   .....

**Comment by necrose99** [comment]
https://github.com/jhunt/clockwork/
https://github.com/jhunt/ztk

https://malwarefixes.com/remove-filesfrog-update-checker/  hmm could be Y the rename...

**Comment by dmolik** [comment]
I've dropped all URIs for filefrog VIA:

https://github.com/D3fy/defiance-overlay/commit/4c3102f5932314b7969157f5743be101b0eb72f5
