### ISSUE TITLE
crun is broken

### ISSUE THREAD

**Issue by ghost** [D3fy/defiance-overlay#14]
app-emulation/crun cannot download distfile

**Comment by dmolik** [comment]
Yes no worries, if you're willing to a couple of days, crun will be coming to the mainline tree.

Feel free to let me know if there are any other packages in this repo that you would like to see in mainline as well

**Comment by dmolik** [comment]
just waiting on upstream merge https://github.com/gentoo/gentoo/pull/13597

**Comment by dmolik** [comment]
Done, finally
